import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { LoadingProvider } from "./(context)/LoadingContext";
import GlobalLoaderProvider from "@/components/ui/global-loader-provider";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          <LoadingProvider>
            {children}
            <GlobalLoaderProvider />
          </LoadingProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
